// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Connection information connection
//
// swagger:model connection
type Connection struct {

	// DateConnect
	// Required: true
	DateConnect *string `json:"DateConnect"`

	// idnav
	// Required: true
	IP *string `json:"Ip"`
}

// Validate validates this connection
func (m *Connection) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateConnect(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Connection) validateDateConnect(formats strfmt.Registry) error {

	if err := validate.Required("DateConnect", "body", m.DateConnect); err != nil {
		return err
	}

	return nil
}

func (m *Connection) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("Ip", "body", m.IP); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this connection based on context it is used
func (m *Connection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Connection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Connection) UnmarshalBinary(b []byte) error {
	var res Connection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
